name: PlayerProfileManager
version: ${project.version}
main: com.kingfrozo.inv.Main
api-version: 1.16
load: STARTUP
depend:
  - ItemsAdder
commands:
  stopredis:
    description: Shut down redis. Only use to reload the PlayerProfile plugin
    usage: /stopredis
    permission: playerprofilesmanager.stopredis